region                 = "us-central1"
project_id             = "ornate-lens-405106"
vpc_name               = "main-vpc"
subnet_name            = "main-subnet"
subnet_ipcidr_range    = "10.240.0.0/24"
external_firewall_name = "external-firewall"
internal_firewall_name = "internal-firewall"
